export const exercisesByMuscle = {
  chest: [
    {
      id: 1,
      name: 'Bench Press',
      sets: 4,
      reps: 10,
      muscle: 'Chest · Triceps',
      equipment: 'Barbell',
      difficulty: 'intermediate',
      emoji: '🏋️',
    },
    {
      id: 2,
      name: 'Incline Bench Press',
      sets: 3,
      reps: 10,
      muscle: 'Upper Chest',
      equipment: 'Barbell',
      difficulty: 'intermediate',
      emoji: '🏋️',
    },
    {
      id: 3,
      name: 'Pec Deck',
      sets: 3,
      reps: 12,
      muscle: 'Chest · Inner',
      equipment: 'Machine',
      difficulty: 'beginner',
      emoji: '🔄',
    },
    {
      id: 4,
      name: 'Cable Fly',
      sets: 3,
      reps: 15,
      muscle: 'Chest · Stretch',
      equipment: 'Cable',
      difficulty: 'beginner',
      emoji: '💪',
    },
    {
      id: 5,
      name: 'Push Ups',
      sets: 3,
      reps: 20,
      muscle: 'Chest · Shoulders',
      equipment: 'Bodyweight',
      difficulty: 'beginner',
      emoji: '⬇️',
    },
  ],

  legs: [
    {
      id: 6,
      name: 'Squats',
      sets: 4,
      reps: 10,
      muscle: 'Quads · Glutes',
      equipment: 'Barbell',
      difficulty: 'intermediate',
      emoji: '🏋️',
    },
    {
      id: 7,
      name: 'Leg Press',
      sets: 3,
      reps: 12,
      muscle: 'Quads · Hamstrings',
      equipment: 'Machine',
      difficulty: 'beginner',
      emoji: '🦵',
    },
    {
      id: 8,
      name: 'Romanian Deadlift',
      sets: 3,
      reps: 10,
      muscle: 'Hamstrings · Glutes',
      equipment: 'Barbell',
      difficulty: 'intermediate',
      emoji: '🏋️',
    },
    {
      id: 9,
      name: 'Leg Extension',
      sets: 3,
      reps: 15,
      muscle: 'Quads',
      equipment: 'Machine',
      difficulty: 'beginner',
      emoji: '🔄',
    },
    {
      id: 10,
      name: 'Standing Calf Raise',
      sets: 4,
      reps: 15,
      muscle: 'Calves',
      equipment: 'Machine',
      difficulty: 'beginner',
      emoji: '⬆️',
    },
  ],

  back: [
    {
      id: 11,
      name: 'Deadlift',
      sets: 4,
      reps: 8,
      muscle: 'Back · Hamstrings',
      equipment: 'Barbell',
      difficulty: 'advanced',
      emoji: '🏋️',
    },
    {
      id: 12,
      name: 'Lat Pulldown',
      sets: 3,
      reps: 12,
      muscle: 'Lats · Biceps',
      equipment: 'Cable',
      difficulty: 'beginner',
      emoji: '⬇️',
    },
    {
      id: 13,
      name: 'Machine Rows',
      sets: 3,
      reps: 12,
      muscle: 'Mid Back',
      equipment: 'Machine',
      difficulty: 'beginner',
      emoji: '🔄',
    },
    {
      id: 14,
      name: 'Weighted Pull Ups',
      sets: 3,
      reps: 8,
      muscle: 'Lats · Biceps',
      equipment: 'Bodyweight',
      difficulty: 'advanced',
      emoji: '💪',
    },
    {
      id: 15,
      name: 'Rear Delt Fly',
      sets: 3,
      reps: 15,
      muscle: 'Rear Delts · Back',
      equipment: 'Dumbbell',
      difficulty: 'beginner',
      emoji: '🦾',
    },
  ],

  arms: [
    {
      id: 16,
      name: 'Preacher Curls',
      sets: 3,
      reps: 12,
      muscle: 'Biceps',
      equipment: 'Barbell',
      difficulty: 'beginner',
      emoji: '💪',
    },
    {
      id: 17,
      name: 'Spider Curls',
      sets: 3,
      reps: 12,
      muscle: 'Biceps · Peak',
      equipment: 'Dumbbell',
      difficulty: 'beginner',
      emoji: '🦾',
    },
    {
      id: 18,
      name: 'Triceps Pressdown',
      sets: 3,
      reps: 12,
      muscle: 'Triceps',
      equipment: 'Cable',
      difficulty: 'beginner',
      emoji: '⬇️',
    },
    {
      id: 19,
      name: 'Cable Head Extension',
      sets: 3,
      reps: 12,
      muscle: 'Triceps · Long Head',
      equipment: 'Cable',
      difficulty: 'beginner',
      emoji: '🔄',
    },
  ],

  shoulders: [
    {
      id: 20,
      name: 'Lateral Raise',
      sets: 3,
      reps: 15,
      muscle: 'Side Delts',
      equipment: 'Dumbbell',
      difficulty: 'beginner',
      emoji: '🦾',
    },
    {
      id: 21,
      name: 'Overhead Press',
      sets: 4,
      reps: 10,
      muscle: 'Shoulders · Triceps',
      equipment: 'Barbell',
      difficulty: 'intermediate',
      emoji: '🏋️',
    },
    {
      id: 22,
      name: 'Face Pulls',
      sets: 3,
      reps: 15,
      muscle: 'Rear Delts · Rotator',
      equipment: 'Cable',
      difficulty: 'beginner',
      emoji: '🔄',
    },
  ],

  core: [
    {
      id: 23,
      name: 'Ab Crunch',
      sets: 3,
      reps: 20,
      muscle: 'Abs',
      equipment: 'Machine',
      difficulty: 'beginner',
      emoji: '🫀',
    },
    {
      id: 24,
      name: 'Plank',
      sets: 3,
      reps: 60,
      muscle: 'Core · Abs',
      equipment: 'Bodyweight',
      difficulty: 'beginner',
      emoji: '⬇️',
    },
    {
      id: 25,
      name: 'Hanging Leg Raise',
      sets: 3,
      reps: 15,
      muscle: 'Lower Abs',
      equipment: 'Bodyweight',
      difficulty: 'intermediate',
      emoji: '💪',
    },
  ],

};